version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: credit_db
    ports:
      - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
